import Head from 'next/head';
import {useQuery} from '@tanstack/react-query';
import Footer from '../components/footer';
import {FC, useState} from 'react';
import fetchPhoneticTranslation from '../requests/fetch-phonetic-translation';

const SelectWord: FC<{ wordSet: string[], wordId: string }> = ({wordSet, wordId}) => {
    const [selectedWordIndex, setSelectedWordIndex] = useState(0)
    const [showWordChoices, setShowWordChoices] = useState(false)

    const toggleWordChoices = () => {
        setShowWordChoices(prevState => !prevState);
    };

    const handleSelectWord = (i: number) => () => {
        setSelectedWordIndex(i);
        setShowWordChoices(false);
    };

    return (
        <div className='inline relative'>
            <button onClick={toggleWordChoices} className='text-blue-600'>{wordSet[selectedWordIndex]}</button>
            {showWordChoices
                ? (
                    <div className='absolute w-auto top-5 left-0 bg-gray-200 shadow'>
                        {wordSet.map((word, i) =>
                            <button
                                key={`${wordId}_${word}`}
                                onClick={handleSelectWord(i)}
                                className='whitespace-nowrap bg-gray-200 block w-auto min-w-full p-1 border-b border-b-gray-300 hover:bg-gray-400 last-of-type:border-0'
                            >
                                {word}
                            </button>
                        )}
                    </div>
                )
                : null}
        </div>
    );
};

const Home = () => {
    let timer;
    const [text, setText] = useState('');
    const [languageCode, setLanguageCode] = useState('en_UK');

    const {data, isError, error, isSuccess} = useQuery({
        queryKey: ['translation', text, languageCode],
        queryFn: () => fetchPhoneticTranslation(languageCode, text),
        initialData: {translation: []}
    });

    const handleInput = (event) => {
        clearTimeout(timer);
        const newText = event.target.value;
        timer = setTimeout(() => {
            setText(newText);
        }, 400);
    };

    const handleSelect = (event) => {
        setLanguageCode(event.target.value);
    };

    return (
        <div className="flex flex-col h-full">
            <Head>
                <title>Phonetic Translator</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="px-20 py-10 max-w-[80ch]">
                <h1 className='text-2xl'>Phonetic Translator</h1>
                <div className="my-10">
                    <label
                        htmlFor="countries"
                        className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                    >Select a Language</label>
                    <select
                        onChange={handleSelect}
                        defaultValue='en_UK'
                        id="countries"
                        className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                    >
                        <option value="en_UK">English</option>
                        <option value="de">German</option>
                        <option value="fr_FR">French</option>
                        <option value="es_ES">Spanish</option>
                        <option value="sv">Swedish</option>
                        <option value="it">Italian</option>
                        <option value="da">Danish</option>
                        <option value="fi">Finnish</option>
                        <option value="hu">Hungarian</option>
                        <option value="is">Icelandic</option>
                        <option value="el">Greek</option>
                        <option value="ru">Russian</option>
                        <option value="yi">Yiddish</option>
                        <option value="la">Latin</option>
                    </select>
                </div>
                <div className="my-10">
                    <label
                        htmlFor="input"
                        className="block mb-2 text-sm font-medium text-gray-900"
                    >Input</label>
                    <textarea
                        id="input"
                        onChange={handleInput}
                        className="min-h-[260px] block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500"
                        placeholder="Enter text to translate"
                    />
                </div>
                <div className="my-10">
                    <>
                        <label
                            className="block mb-2 text-sm font-medium text-gray-900"
                        >Output</label>
                        <div
                            className="min-h-[260px] block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 outline-none focus:outline-none"
                        >
                            {isSuccess ? (data?.translation).map(
                                (wordSet, i) => (wordSet.length === 1
                                        ? <span key={`w_${i}`}>{wordSet}</span>
                                        : <SelectWord wordSet={wordSet} wordId={`w_${i}`} key={`w_${i}`}/>
                                )) : null}
                        </div>
                    </>
                </div>
            </main>
            <Footer/>
        </div>
    );
};

export default Home
